stages:
  - build
  - deploy

variables:
  REPO_URL: quay.io/gscheffe
  DOCKER_REGISTRY_USER: $CI_REGISTRY_USER
  DOCKER_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD

build:
  stage: build
  image: docker:stable

  services:
    - docker:dind
  
  script:
    - chmod +x buildAll.sh pushAll.sh 
    - ./buildAll.sh
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $REPO_URL
    - ./pushAll.sh

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - apk add --update curl
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl deploy_script_cloud.sh
    - mv kubectl /usr/local/bin/
    - ./deploy_script_cloud.sh
