apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend-php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-php
  template:
    metadata:
      labels:
        app: backend-php
        version: "1.1"
    spec:
      containers:
      - name: backend
        image: quay.io/gscheffe/dio-backend:1.1
        ports:
        - containerPort: 80
